import { existsSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { RELAY_TOOL_METAS } from '../src/mcp.js';
import { ensureSkill, generateSkillMd, paramSummary, refreshSkillIfStale, writeSkill } from '../src/skill.js';

describe('generateSkillMd', () => {
  const md = generateSkillMd();

  it('has valid single-line frontmatter with a small resident cost', () => {
    expect(md.startsWith('---\n')).toBe(true);
    const frontmatter = md.split('---\n')[1] ?? '';
    const lines = frontmatter.trim().split('\n');
    expect(lines[0]).toBe('name: agent-debug');
    expect(lines[1]).toMatch(/^description: /);
    expect(lines).toHaveLength(2); // description must stay one line for the frontmatter parser
    // The frontmatter is the only part resident in every conversation — keep it small.
    expect(frontmatter.length).toBeLessThan(600);
  });

  it('lists every descriptor tool plus the relay-side tabs tools', () => {
    for (const meta of RELAY_TOOL_METAS) expect(md).toContain(`\`${meta.name}\``);
    expect(md).toContain('`tabs_list`');
    expect(md).toContain('`tabs_open`');
  });

  it('marks exactly the mutation tools', () => {
    for (const meta of RELAY_TOOL_METAS) {
      const line = md.split('\n').find((l) => l.startsWith(`- \`${meta.name}\``));
      expect(line, meta.name).toBeDefined();
      expect(line!.includes('[mutation]'), meta.name).toBe(meta.mutation);
    }
  });

  it('stamps a version marker below the frontmatter', () => {
    expect(md).toMatch(/^<!-- generated by agent-debug-mcp v\d+\.\d+\.\d+ -->$/m);
    expect(generateSkillMd({ version: '9.9.9-test' })).toContain('<!-- generated by agent-debug-mcp v9.9.9-test -->');
  });

  it('teaches the call CLI', () => {
    expect(md).toContain('agent-debug-mcp call <tool>');
    expect(md).toContain('--list');
    expect(md).toContain('--describe');
    expect(md).toContain('untrusted');
  });
});

describe('paramSummary', () => {
  it('stars required params and stays empty for empty schemas', () => {
    expect(paramSummary({ type: 'object', properties: {} })).toBe('');
    expect(paramSummary({ type: 'object', properties: { a: {}, b: {} }, required: ['a'] })).toBe(' (a*, b)');
  });
});

describe('writeSkill', () => {
  it('creates the skill file under .claude/skills and reports updates', () => {
    const cwd = mkdtempSync(join(tmpdir(), 'dtmcp-skill-'));
    const first = writeSkill({ cwd });
    expect(first.created).toBe(true);
    expect(first.path).toBe(join(cwd, '.claude/skills/agent-debug/SKILL.md'));
    expect(existsSync(first.path)).toBe(true);
    expect(readFileSync(first.path, 'utf8')).toBe(generateSkillMd());
    expect(writeSkill({ cwd }).created).toBe(false);
  });
});

describe('refreshSkillIfStale', () => {
  it('rewrites only a marker-carrying file whose version differs, and never creates one', () => {
    const cwd = mkdtempSync(join(tmpdir(), 'dtmcp-refresh-'));
    expect(refreshSkillIfStale({ cwd })).toBeNull(); // no file → nothing

    const { path } = writeSkill({ cwd, version: '0.0.1' });
    const r = refreshSkillIfStale({ cwd, version: '0.0.2' });
    expect(r).toMatchObject({ path, from: '0.0.1', to: '0.0.2' });
    expect(readFileSync(path, 'utf8')).toContain('v0.0.2 -->');
    expect(refreshSkillIfStale({ cwd, version: '0.0.2' })).toBeNull(); // up to date → untouched

    writeFileSync(path, '---\nname: agent-debug\n---\nhand-edited, no marker\n');
    expect(refreshSkillIfStale({ cwd, version: '0.0.3' })).toBeNull(); // user owns it now
    expect(readFileSync(path, 'utf8')).toContain('hand-edited');
  });
});

describe('ensureSkill', () => {
  it('creates when missing, updates when stale, leaves current and hand-edited files alone', () => {
    const cwd = mkdtempSync(join(tmpdir(), 'dtmcp-ensure-'));
    const created = ensureSkill({ cwd, version: '0.0.1' });
    expect(created).toMatchObject({ action: 'created', path: join(cwd, '.claude/skills/agent-debug/SKILL.md') });
    expect(existsSync(created!.path)).toBe(true);

    expect(ensureSkill({ cwd, version: '0.0.1' })).toBeNull(); // up to date
    expect(ensureSkill({ cwd, version: '0.0.2' })).toMatchObject({ action: 'updated', from: '0.0.1', to: '0.0.2' });

    writeFileSync(created!.path, 'hand-edited, no marker\n');
    expect(ensureSkill({ cwd, version: '0.0.3' })).toBeNull(); // exists but user-owned → untouched
    expect(readFileSync(created!.path, 'utf8')).toBe('hand-edited, no marker\n');
  });
});
