/** Generates docs/TOOLS.md from the descriptor modules so the reference never drifts from the code. */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(fileURLToPath(new URL('.', import.meta.url)), '..');
import { reactToolMetas } from '../packages/tools-react/src/descriptors.ts';
import { tanstackQueryToolMetas } from '../packages/tools-tanstack-query/src/descriptors.ts';
import { tanstackRouterToolMetas } from '../packages/tools-tanstack-router/src/descriptors.ts';
import { PROMPTS } from '../packages/relay/src/prompts.ts';
import { createPlaywrightBridge } from '../packages/relay/src/playwright.ts';

type Schema = { properties?: Record<string, Record<string, unknown>>; required?: string[] };
const metas = [...reactToolMetas, ...tanstackQueryToolMetas, ...tanstackRouterToolMetas];

// The embedded Playwright MCP tools (renamed browser_* → page_*): instantiate the real bridge offline
// (with a cdpEndpoint nothing touches a browser until a tool call) so the list never drifts.
const bridge = await createPlaywrightBridge({
  cdpUrl: 'http://127.0.0.1:1/cdp/docs',
  existingNames: new Set([...metas.map((m) => m.name), 'tabs_list', 'tabs_open']),
  version: 'docs',
});
const browserRows = bridge.tools
  .map((t) => `| \`${t.name}\`${t.annotations.readOnlyHint ? ' — read-only' : ''} | ${(t.description.split(/(?<=\.)\s/)[0] ?? '').replace(/\|/g, '\\|')} |`)
  .join('\n');

const typeOf = (p: Record<string, unknown>): string => {
  if (p.enum) return (p.enum as unknown[]).map((v) => `\`${String(v)}\``).join(' \\| ');
  const t = p.type;
  if (Array.isArray(t)) return t.join(' \\| ');
  if (t === 'array') return `array${p.items && (p.items as { type?: unknown }).type ? `<${String((p.items as { type: unknown }).type)}>` : ''}`;
  return typeof t === 'string' ? t : 'any';
};

const params = (schema: Schema): string => {
  const props = schema.properties ?? {};
  const req = new Set(schema.required ?? []);
  const rows = Object.entries(props).map(([k, p]) => {
    const dflt = p.default !== undefined ? ` (default \`${JSON.stringify(p.default)}\`)` : '';
    return `| \`${k}\`${req.has(k) ? ' *' : ''} | ${typeOf(p)} | ${String(p.description ?? '')}${dflt} |`;
  });
  return rows.length ? ['| Param | Type | Description |', '|---|---|---|', ...rows].join('\n') : '_No parameters._';
};

const groups: Record<string, typeof metas> = {};
for (const m of metas) (groups[m.capability] ??= []).push(m);
const order = ['page', 'react', 'tanstack_query', 'tanstack_router'];
const titles: Record<string, string> = { page: 'Page / tabs', react: 'React', tanstack_query: 'TanStack Query', tanstack_router: 'TanStack Router' };

let md = `# Tool reference

_Generated by \`pnpm docs:tools\` from the \`descriptors.ts\` modules — do not edit by hand._

Every tool below also accepts an optional \`tab\` (string, \`t<id>\` from \`tabs_list\`) injected by the relay; it is
required only when more than one tab is attached. Tools marked **mutation** are gated per origin.
Results arrive as JSON text plus \`structuredContent\` = \`{ tab, doc, result }\`; errors as \`{ error: ToolError }\`.

## Prompts

The relay also serves MCP **prompts** — the debugging loop (reproduce → locate → inspect → fix → verify) as an exact
tool sequence. Pick them from your client's prompt list (Claude Code: \`/mcp__<server>__<prompt>\`). All arguments are optional strings.

${PROMPTS.map((p) => `### \`${p.name}\` — ${p.title}\n${p.description}\n\n${p.args.map((a) => `- \`${a.name}\` — ${a.description}`).join('\n')}\n`).join('\n')}
## Relay tools

### \`tabs_list\`
List attached tabs with url, title, capabilities (\`react\`, \`tanstack_query\`, \`tanstack_router\`), whether mutations are allowed and whether the extension is connected. Call this first. _No parameters._

### \`tabs_open\` — mutation
Open a URL in a new tab (localhost / 127.0.0.1 / *.local or allowlisted origins) and wait until Agent Debug MCP attached.

| Param | Type | Description |
|---|---|---|
| \`url\` * | string | Absolute URL to open. |
| \`waitForCapability\` | \`react\` \\| \`tanstack_query\` \\| \`tanstack_router\` | Wait until this capability is reported (up to waitMs). |
| \`waitMs\` | integer | How long to wait for the tab to attach (default \`10000\`). |

### Browser automation (embedded Playwright MCP)
Screenshots, clicks, typing, navigation, console and network are built in: an embedded
[Playwright MCP](https://github.com/microsoft/playwright-mcp) drives the *same* attached tabs over the relay's own CDP
endpoint, re-exported as \`page_*\` (renamed from \`browser_*\` so they never clash with a separately installed
Playwright MCP; parameters are documented upstream). Playwright's \`browser_snapshot\` is skipped: the relay's own
\`page_snapshot\` below returns the outline, and its CSS selectors work directly as the \`target\` of \`page_click\` /
\`page_type\`. \`--no-playwright\` disables these tools; an external CDP client displaces them while connected.

| Tool | Does |
|---|---|
${browserRows}
`;

for (const cap of order) {
  const list = groups[cap];
  if (!list) continue;
  md += `\n## ${titles[cap]} (capability \`${cap}\`)\n`;
  for (const m of list) {
    md += `\n### \`${m.name}\`${m.mutation ? ' — mutation' : ''}${m.annotations.readOnlyHint ? ' — read-only' : ''}\n${m.description}\n\n${params(m.inputSchema as Schema)}\n`;
    if (m.timeoutMs) md += `\n_Relay timeout: ${Math.round(m.timeoutMs / 1000)} s._\n`;
  }
}
md += `\n---\n${metas.length + 3 + bridge.tools.length} tools (${bridge.tools.length} of them embedded browser tools). \`*\` = required.\n`;
writeFileSync(resolve(ROOT, 'docs/TOOLS.md'), md);
await bridge.close();
console.log(`wrote docs/TOOLS.md (${metas.length + 3 + bridge.tools.length} tools, ${bridge.tools.length} embedded browser tools)`);
